# Generated by Django 5.0.2 on 2024-02-16 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MomCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('owners_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kitten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age_in_months', models.IntegerField()),
                ('momcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kittens', to='cats_and_kittens.momcat')),
            ],
        ),
    ]
